version: '3.4'

services:
  mongo:
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=root
      #- MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=DbName
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db
      #- ./mongovolume/configdb:/data/configdb
  mssql:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - ${APPDATA}/mssqlvolume/data:/var/opt/mssql/data
      - ${APPDATA}/mssqlvolume/log:/var/opt/mssql/log
      - ${APPDATA}/mssqlvolume/secrets:/var/opt/mssql/secrets
  coretemplate.application.ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MainConnection_ConnectionString=${ONKA_MAINCONNECTION_CS:-Server=mssql;Database=DbName;User Id=sa;Password=Pass@word}
      - MainConnection_Provider=${ONKA_MAINCONNECTION_PROVIDER:-mssql}
      - MongoConnection_ConnectionString=${ONKA_MONGOCONNECTION_CS:-mongodb://mongo:27017}
      - MongoConnection_DatabaseName=${ONKA_MONGOCONNECTION_DATABASENAME:-DbName}
      - ElasticConnection_Url=${ONKA_ELASTICCONNECTION_URL:-http://elasticsearch:9200}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5240:80"
      - "6240:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  coretemplate.application.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MainConnection_ConnectionString=${ONKA_MAINCONNECTION_CS:-Server=mssql;Database=DbName;User Id=sa;Password=Pass@word}
      - MainConnection_Provider=${ONKA_MAINCONNECTION_PROVIDER:-mssql}
      - MongoConnection_ConnectionString=${ONKA_MONGOCONNECTION_CS:-mongodb://mongo:27017}
      - MongoConnection_DatabaseName=${ONKA_MONGOCONNECTION_DATABASENAME:-DbName}
      - ElasticConnection_Url=${ONKA_ELASTICCONNECTION_URL:-http://elasticsearch:9200}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5250:80"
      - "6250:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  coretemplate.moduleaccount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MainConnection_ConnectionString=${ONKA_MAINCONNECTION_CS:-Server=mssql;Database=DbName;User Id=sa;Password=Pass@word}
      - MainConnection_Provider=${ONKA_MAINCONNECTION_PROVIDER:-mssql}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5251:80"
      - "6251:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  coretemplate.moduleadmin.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MainConnection_ConnectionString=${ONKA_MAINCONNECTION_CS:-Server=mssql;Database=DbName;User Id=sa;Password=Pass@word}
      - MainConnection_Provider=${ONKA_MAINCONNECTION_PROVIDER:-mssql}
      - MongoConnection_ConnectionString=${ONKA_MONGOCONNECTION_CS:-mongodb://mongo:27017}
      - MongoConnection_DatabaseName=${ONKA_MONGOCONNECTION_DATABASENAME:-DbName}
      - ElasticConnection_Url=${ONKA_ELASTICCONNECTION_URL:-http://elasticsearch:9200}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5252:80"
      - "6252:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  coretemplate.moduletest.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MainConnection_ConnectionString=${ONKA_MAINCONNECTION_CS:-Server=mssql;Database=DbName;User Id=sa;Password=Pass@word}
      - MainConnection_Provider=${ONKA_MAINCONNECTION_PROVIDER:-mssql}
      - MongoConnection_ConnectionString=${ONKA_MONGOCONNECTION_CS:-mongodb://mongo:27017}
      - MongoConnection_DatabaseName=${ONKA_MONGOCONNECTION_DATABASENAME:-DbName}
      - ElasticConnection_Url=${ONKA_ELASTICCONNECTION_URL:-http://elasticsearch:9200}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5253:80"
      - "6253:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  mssqlvolume:
  mongovolume:
networks:
  default:
    external:
        name: docker_default