version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-management
    ports: 
      - 15672:15672
    volumes: 
      - rabbitmqvolume:/var/lib/rabbitmq
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    depends_on:
      - mongo
    links:
      - mongo
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    volumes:
      - elasticsearchvolume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports: 
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200      
    depends_on:
      - elasticsearch
volumes: 
  rabbitmqvolume:
  elasticsearchvolume:
        