version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always  
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
  coretemplate.application.ocelotapigateway:
    image: ${DOCKER_REGISTRY-}coretemplateapplicationocelotapigateway
    build:
      context: ../..
      dockerfile: dotnet-core-template/Application/CoreTemplate.Application.OcelotApiGateway/Dockerfile
    depends_on:
      - mssql
  coretemplate.application.api:
    image: ${DOCKER_REGISTRY-}coretemplateapplicationapi
    build:
      context: ../..
      dockerfile: dotnet-core-template/Application/CoreTemplate.Application.API/Dockerfile
    depends_on:
      - mssql
  moduleadmin.api:
    image: ${DOCKER_REGISTRY-}moduleadminapi
    build:
      context: ../..
      dockerfile: dotnet-core-template/Modules/ModuleAdmin.API/Dockerfile
    depends_on:
      - mssql
  moduleaccount.api:
    image: ${DOCKER_REGISTRY-}moduleaccountapi
    build:
      context: ../..
      dockerfile: dotnet-core-template/Modules/ModuleAccount.API/Dockerfile
    depends_on:
      - mssql